export const NIM_PROXY_URL = '';
export const BODY_REGION = ['head', 'abdomen', 'chest/thorax', 'pelvis/lower'];

export const ANATOMY_LIST = [
  'liver',
  'kidney',
  'spleen',
  'pancreas',
  'right kidney',
  'aorta',
  'inferior vena cava',
  'right adrenal gland',
  'left adrenal gland',
  'gallbladder',
  'esophagus',
  'stomach',
  'duodenum',
  'left kidney',
  'bladder',
  'prostate or uterus',
  'portal vein and splenic vein',
  'rectum',
  'small bowel',
  'lung',
  'bone',
  'brain',
  'lung tumor',
  'pancreatic tumor',
  'hepatic vessel',
  'hepatic tumor',
  'colon cancer primaries',
  'left lung upper lobe',
  'left lung lower lobe',
  'right lung upper lobe',
  'right lung middle lobe',
  'right lung lower lobe',
  'vertebrae L5',
  'vertebrae L4',
  'vertebrae L3',
  'vertebrae L2',
  'vertebrae L1',
  'vertebrae T12',
  'vertebrae T11',
  'vertebrae T10',
  'vertebrae T9',
  'vertebrae T8',
  'vertebrae T7',
  'vertebrae T6',
  'vertebrae T5',
  'vertebrae T4',
  'vertebrae T3',
  'vertebrae T2',
  'vertebrae T1',
  'vertebrae C7',
  'vertebrae C6',
  'vertebrae C5',
  'vertebrae C4',
  'vertebrae C3',
  'vertebrae C2',
  'vertebrae C1',
  'trachea',
  'left iliac artery',
  'right iliac artery',
  'left iliac vena',
  'right iliac vena',
  'colon',
  'left rib 1',
  'left rib 2',
  'left rib 3',
  'left rib 4',
  'left rib 5',
  'left rib 6',
  'left rib 7',
  'left rib 8',
  'left rib 9',
  'left rib 10',
  'left rib 11',
  'left rib 12',
  'right rib 1',
  'right rib 2',
  'right rib 3',
  'right rib 4',
  'right rib 5',
  'right rib 6',
  'right rib 7',
  'right rib 8',
  'right rib 9',
  'right rib 10',
  'right rib 11',
  'right rib 12',
  'left humerus',
  'right humerus',
  'left scapula',
  'right scapula',
  'left clavicula',
  'right clavicula',
  'left femur',
  'right femur',
  'left hip',
  'right hip',
  'sacrum',
  'left gluteus maximus',
  'right gluteus maximus',
  'left gluteus medius',
  'right gluteus medius',
  'left gluteus minimus',
  'right gluteus minimus',
  'left autochthon',
  'right autochthon',
  'left iliopsoas',
  'right iliopsoas',
  'left atrial appendage',
  'brachiocephalic trunk',
  'left brachiocephalic vein',
  'right brachiocephalic vein',
  'left common carotid artery',
  'right common carotid artery',
  'costal cartilages',
  'heart',
  'left kidney cyst',
  'right kidney cyst',
  'prostate',
  'pulmonary vein',
  'skull',
  'spinal cord',
  'sternum',
  'left subclavian artery',
  'right subclavian artery',
  'superior vena cava',
  'thyroid gland',
  'vertebrae S1',
  'bone lesion',
  'kidney mass',
  'liver tumor',
  'vertebrae L6',
  'airway',
];
